### PR TITLE
Bacula: Configure db backend in Wato

### LINKED ISSUE #1: bacula-jobs / pgsql
Hi Basti :-)

die meisten Bacula DBs laufen mit PostgreSQL.
Ich hab den Query angepasst

```
#!/bin/sh
echo "<<<bacula_jobs:sep(9)>>>"
echo "Select JobId, Name, JobStatus, EndTime FROM Job WHERE EndTime BETWEEN NOW() - interval '30 days' AND NOW();" | sudo -u postgres psql --tuples-only -AF $'\t'  bacula bacula
```

Was fehlt ist ne Auto-detection, ob MySQL oder PostgreSQL genutzt wird.
Es gibt ne Configdatei, in der der DB-Connect definiert wird, aber die Configs koennen includes, d.h. kaum zu schaffen, das per grep gut zu finden. Ich hab auch kein Kommando gefunden, um die config per bconsole anzuzeigen.

Was mein Vorschlag waere, als "gut genug"-Loesung:   

Per LDD nachschauen:

```
# ldd `which bacula-dir` | grep -i -e libmysqlclient -e libpq
	libpq.so.5 => /usr/local/lib/libpq.so.5 (0x803127000)
```

Waere das als Patch OK? Ich wuerd drei Faelle beachten:

1. MySQL gefunden (passender Query, ggf. passender sep())
2. PostgreSQL gefunden (passender Query, ggf. passender sep())
3. beides nicht gefunden (Plugin liefert dann einfach keine Daten)

evtl. gab es mal SQLite Support aber das war eh nicht fuer Prod und ich hab das noch niemals in echt gesehen.

Gruesse

### PR DESCRIPTION
**Pull request by robertoschwald**
- fixes #1 
- Added Agent rule config options for backend_type, dbname, dbuser, dbhost
- Supports MySQL and PostgreSQL
- Db binary paths are not hardcoded anymore
- Renamed bacula.sh to bacula_jobs, as plugins shouldn’t have a file extension (https://checkmk.de/cms_dev_guidelines.html)
- Added manpage
- Generates config file automatically when using the bakery (yay!)

wato_rules

### CODE REVIEW

**Comment by robertoschwald** [comment]
If one wants to test it, give it a try. 
https://github.com/robertoschwald/Check_MK-Treasures/releases/tag/1.2.PR14

**Comment by Bastian-Kuhn** [comment]
Thank you very much for the improvements. I merge it!

**Comment by robertoschwald** [comment]
Wait a bit. There is still one issue to fix. Will do romorrow

**Comment by robertoschwald** [comment]
Too late. You get another pr tomorrow

**Pull request merged**
