### PR TITLE
Pull request for new MKP

### PR DESCRIPTION
**Pull request by carkle1971**
Added array info like software version, software revision and Array ID. Added volume usage data, volume performance data and volume details like dedup and so on. The volume data is created in three separate services. I can not seem to get them in one service. I will keep trying for that.

### CODE REVIEW

**Comment by Bastian-Kuhn** [comment]
Hi,

Thanks for the Pull request. Sadly it's seams your Editor reformated the whole code.
We use just 4 Spaces for intents. Can you please fix that, the file changes normaly should only show what you have changed and not the whole file :)

**Comment by carkle1971** [comment]
I work with Visual Studio Code. I downloaded the files and changed them then. I will have a look tomorrow

Met vriendelijke groet, Kind Regards, Bien à vous, Med vennlig hilsen, Mit freundlichen Grüßen,
Carlo Kleinloog

From: Bastian Kuhn ***@***.***>
Sent: Wednesday, January 25, 2023 7:13 PM
To: Bastian-Kuhn/Check_MK-Treasures ***@***.***>
Cc: Kleinloog, Carlo (Bilfinger Shared Services B.V.) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [Bastian-Kuhn/Check_MK-Treasures] Pull request for new MKP (PR #44)

This e-mail is from an external source - be cautious, particularly with links, attachments and unusual requests.

Hi,

Thanks for the Pull request. Sadly it's seams your Editor reformated the whole code.
We use just 4 Spaces for intents. Can you please fix that, the file changes normaly should only show what you have changed and not the whole file :)

**Comment by carkle1971** [comment]
Bastian,

I updated just now. Can you please check if it is okay now?

Met vriendelijke groet, Kind Regards, Bien à vous, Med vennlig hilsen, Mit freundlichen Grüßen,
Carlo Kleinloog

From: Bastian Kuhn ***@***.***>
Sent: Wednesday, January 25, 2023 7:21 PM
To: Bastian-Kuhn/Check_MK-Treasures ***@***.***>
Cc: Kleinloog, Carlo (Bilfinger Shared Services B.V.) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [Bastian-Kuhn/Check_MK-Treasures] Pull request for new MKP (PR #44)

This e-mail is from an external source - be cautious, particularly with links, attachments and unusual requests.

Perfect, thank you.

If you work with such a suite, there should be a Python Extension.
And there you can 100% activate pylint, which will solve almost every formatting Problem I complained in the review :)

**Comment by Bastian-Kuhn** [comment]
Hi,

you haven't updated the Pull Request yet. It's still with the old commits. 

Best Bastian

**Comment by carkle1971** [comment]
I am updating soon.

Met vriendelijke groet, Kind Regards, Bien à vous, Med vennlig hilsen, Mit freundlichen Grüßen,
Carlo Kleinloog

From: Bastian Kuhn ***@***.***>
Sent: Tuesday, January 31, 2023 8:11 AM
To: Bastian-Kuhn/Check_MK-Treasures ***@***.***>
Cc: Kleinloog, Carlo (Bilfinger Shared Services B.V.) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [Bastian-Kuhn/Check_MK-Treasures] Pull request for new MKP (PR #44)

This e-mail is from an external source - be cautious, particularly with links, attachments and unusual requests.

Hi,

you haven't updated the Pull Request yet. It's still with the old commits.

Best Bastian

**Comment by carkle1971** [comment]
Creating new request with new files

**Comment by carkle1971** [comment]
Hi Bastian,

Sorry for that. I am new to Github as a contributor. I forked your Check_MK-Treasures, changed and added the files in the pure directory. Created new pull request. I hope this is the correct way. I followed a YouTube video ☺ I am still working on creating one file for the volumes that contains volume data, performance data and details, so we can have one service per volume in Check_MK. It’s good for me to learn Python and Check_MK a bit more.

Met vriendelijke groet, Kind Regards, Bien à vous, Med vennlig hilsen, Mit freundlichen Grüßen,
Carlo Kleinloog

From: Bastian Kuhn ***@***.***>
Sent: Tuesday, January 31, 2023 8:11 AM
To: Bastian-Kuhn/Check_MK-Treasures ***@***.***>
Cc: Kleinloog, Carlo (Bilfinger Shared Services B.V.) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [Bastian-Kuhn/Check_MK-Treasures] Pull request for new MKP (PR #44)

This e-mail is from an external source - be cautious, particularly with links, attachments and unusual requests.

Hi,

you haven't updated the Pull Request yet. It's still with the old commits.

Best Bastian

**Pull request closed without merging**
